[package]
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
build = "build.rs"
license = "Apache-2.0"
name = "node-rodio"
version = "0.0.9"

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
rodio = "0.8.0"
cpal = "0.8.2"

[lib]
crate-type = ["dylib"]
name = "node_rodio"
